sudo: required
services:
  - docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_d05ed5776310_key -iv $encrypted_d05ed5776310_iv -in fibonacci-k8s-303801-ce575144c627.json.enc -out fibonacci-k8s-303801-ce575144c627.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file fibonacci-k8s-303801-ce575144c627.json
  - gcloud config set project fibonacci-k8s-303801
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials fibonacci-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t friendou/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true friendou/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master